### ISSUE TITLE
Tooling issues with the distribution

### ISSUE THREAD

**Issue by karenetheridge** [nigelm/html-formatter#7]
There are inappropriate prereqs listed in the 'build' phase. It looks like these come directly from the `[@NIGELM]` bundle -- these should be moved to develop prereqs (but I think all the plugins properly inject their prereqs now).

**Comment by nigelm** [comment]
Fixed in the `[@NIGELM]` bundle.  Looks like bad historical baggage from long ago.

https://github.com/nigelm/dist-zilla-pluginbundle-nigelm/commit/3f45b10e1cfaf68d32f37a2117ae1b27ac693a35
